baseURL = "https://example.com/"
title = "Yuxuan Nai"
themesDir = "../.."
theme = "hugo-theme-m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "project"
    name = "Project"
    url = "/project/"
    weight = 2
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 3

[params]
  author = "Yuxuan Nai"
  description = " "
  menu_item_separator = " "
  avatar = "photo2.jpg"
  custom_css = ["css/custom.css"]
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/LYtingN"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://x.com/Liyutingnai"

  

  # Default theme
  [params.style]
    darkestColor = "#737c7b"
    darkColor = "#74787a"
    lightColor = "#f1f0ed"
    lightestColor = "#ffffff"
    primaryColor = "#cdd1d3"
    selfsetColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
